[package]
name = "brim-middle"
version = "0.1.0"
edition = "2024"

[dependencies]
brim-ast = { workspace = true }
brim-span = { workspace = true }
brim-index = { workspace = true }
clap = { workspace = true }

[lints]
workspace = true
