[package]
name = "brim-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
backtrace = { workspace = true }
clap = { workspace = true, features = ["derive"] }
colored = { workspace = true }
anstyle = { workspace = true }
toml = { workspace = true }
serde = { workspace = true, features = ["derive"] }
anstream = { workspace = true }
toml_edit = { workspace = true }
tokio = { version = "1.42.0", features = ["rt", "rt-multi-thread", "macros"] }
http-body-util = { workspace = true }
dirs = "5.0.1"
brim-shell = { workspace = true }
ropey = { workspace = true }
thiserror = { workspace = true }
indexmap = "2.7.0"
codespan-reporting = "0.11.1"
unindent = "0.2.3"
term = "1.0.1"
which = "7.0.1"
tracing = { version = "0.1.40", default-features = false, features = ["std"] }
tracing-subscriber = { version = "0.3.18", features = [
    "env-filter",
    "chrono",
    "time",
] }
itertools = "0.13.0"
rand = "0.9.0-beta.1"